# Port
server.port=9090

# Postgre db config
spring.datasource.url=jdbc:postgresql://localhost:5432/smartbank_db_sba
spring.datasource.username=postgres
spring.datasource.password=postgres@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Swagger Config
# Customizing the Swagger Path
springdoc.swagger-ui.path=/api-docs
# Grouping the API
springdoc.api-docs.path=/v3/api-docs